### ISSUE TITLE
Integrate Meta and Drama icons into Vertical Vote Count component; color code to indicate meta or drama status

### ISSUE THREAD

**Issue by timfitzzz** [timfitzzz/twitch-clipcatcher#30]
- [ ] Make Meta and Drama icons that can be used in the same place as UserPips
- [ ] Include Meta and Drama icons at the top of voting list
- [ ] Color code Vertical Vote Count to indicate meta and drama tags
